AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template to create an EC2 instance, security group, and an S3 bucket

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: KeyName
      ImageId: ami-0c55b159cbfafe1f0
      SecurityGroups:
        - InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: MyEC2Instance

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-s3-bucket-example
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled

Outputs:
  InstanceId:
    Description: The Instance ID of the newly created EC2 instance
    Value: MyEC2Instance

  S3BucketName:
    Description: The name of the newly created S3 bucket
    Value: MyS3Bucket